from __future__ import annotations

import asyncio
import json
from collections.abc import AsyncIterator
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, Header, HTTPException
from fastapi.responses import StreamingResponse
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from platform_core.app_builder import build_app_builder_steps, project_workspace
from platform_core.auth import get_current_user
from platform_core.database import SessionLocal, get_db
from platform_core.events import add_audit_event, add_workflow_event
from platform_core.models import Project, ProjectPolicy, User, Workflow, WorkflowEvent, WorkflowRun
from platform_core.permissions import PermissionDenied, require_project_role
from platform_core.queue import enqueue_app_builder
from platform_core.schemas import AppBuilderCreate, AppBuilderResponse, WorkflowEventResponse, WorkflowRunDetailResponse
from platform_core.usage import check_quota
from platform_core.workflows import get_or_create_step_run, normalize_steps

router = APIRouter()


async def project_access(session: AsyncSession, project_id: str, user: User, minimum_role: str) -> Project:
    project = await session.get(Project, project_id)
    try:
        return await require_project_role(session, project, user.id, minimum_role)
    except PermissionDenied as exc:
        raise HTTPException(status_code=404 if project is None else 403, detail=str(exc)) from exc


@router.post(
    "/v1/projects/{project_id}/app-builder",
    response_model=AppBuilderResponse,
    status_code=202,
)
async def create_app_builder_run(
    project_id: str,
    payload: AppBuilderCreate,
    user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_db),
) -> AppBuilderResponse:
    project = await project_access(session, project_id, user, "member")
    allowed, reason, _ = await check_quota(session, project.id, payload.requirements)
    if not allowed:
        raise HTTPException(status_code=429, detail=reason)

    policy = await session.scalar(select(ProjectPolicy).where(ProjectPolicy.project_id == project.id))
    if policy is None:
        session.add(ProjectPolicy(project_id=project.id))

    steps = normalize_steps(build_app_builder_steps(project.id, payload.requirements))
    workflow = Workflow(
        owner_id=user.id,
        project_id=project.id,
        name=payload.name.strip(),
        description=payload.description or "Generated by OpenManus App Builder",
        steps_json=steps,
    )
    session.add(workflow)
    await session.flush()

    run = WorkflowRun(
        workflow_id=workflow.id,
        owner_id=user.id,
        project_id=project.id,
        input=payload.requirements.strip(),
        status="builder_queued",
    )
    session.add(run)
    await session.flush()
    await add_workflow_event(
        session,
        run.id,
        "builder.queued",
        {"status": run.status, "workspace": project_workspace(project.id)},
    )
    await add_audit_event(
        session,
        "builder.created",
        actor_user_id=user.id,
        project_id=project.id,
        metadata={"run_id": run.id, "workflow_id": workflow.id},
    )
    await session.commit()
    try:
        await enqueue_app_builder(run.id)
    except Exception as exc:
        async with SessionLocal() as recovery_session:
            await add_workflow_event(
                recovery_session,
                run.id,
                "builder.queue_deferred",
                {"status": run.status, "reason": str(exc)[:1000]},
            )
            await recovery_session.commit()

    response_workflow = WorkflowRunDetailResponse.model_validate(run)
    return AppBuilderResponse(
        workflow={
            "id": workflow.id,
            "project_id": workflow.project_id,
            "name": workflow.name,
            "description": workflow.description,
            "steps": workflow.steps_json,
            "created_at": workflow.created_at,
            "updated_at": workflow.updated_at,
        },
        workspace=project_workspace(project.id),
    )


@router.get(
    "/v1/projects/{project_id}/app-builder/runs",
    response_model=list[WorkflowRunDetailResponse],
)
async def list_app_builder_runs(
    project_id: str,
    user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_db),
) -> list[WorkflowRunDetailResponse]:
    project = await project_access(session, project_id, user, "viewer")
    runs = await session.scalars(
        select(WorkflowRun)
        .where(
            WorkflowRun.project_id == project.id,
            WorkflowRun.status.in_(["builder_queued", "builder_running", "builder_completed", "builder_failed", "builder_cancelled"]),
        )
        .order_by(WorkflowRun.created_at.desc())
        .limit(50)
    )
    result = []
    for run in runs.all():
        steps = await session.scalars(
            select(get_or_create_step_run.__annotations__.get("return", WorkflowEvent))
        ) if False else None
        result.append(WorkflowRunDetailResponse.model_validate(run))
    return result


@router.get("/v1/app-builder/runs/{run_id}", response_model=WorkflowRunDetailResponse)
async def get_app_builder_run(
    run_id: str,
    user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_db),
) -> WorkflowRunDetailResponse:
    run = await session.get(WorkflowRun, run_id)
    if run is None or not run.status.startswith("builder_"):
        raise HTTPException(status_code=404, detail="App Builder run not found")
    await project_access(session, run.project_id, user, "viewer")
    return WorkflowRunDetailResponse.model_validate(run)


@router.post("/v1/app-builder/runs/{run_id}/cancel", response_model=WorkflowRunDetailResponse)
async def cancel_app_builder_run(
    run_id: str,
    user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_db),
) -> WorkflowRunDetailResponse:
    run = await session.get(WorkflowRun, run_id)
    if run is None or not run.status.startswith("builder_"):
        raise HTTPException(status_code=404, detail="App Builder run not found")
    await project_access(session, run.project_id, user, "member")
    if run.status in {"builder_completed", "builder_failed", "builder_cancelled"}:
        return WorkflowRunDetailResponse.model_validate(run)
    run.cancel_requested = True
    if run.status == "builder_queued":
        run.status = "builder_cancelled"
        run.completed_at = datetime.now(timezone.utc)
        await add_workflow_event(session, run.id, "builder.cancelled", {"status": run.status})
    await add_audit_event(session, "builder.cancel_requested", actor_user_id=user.id, project_id=run.project_id, metadata={"run_id": run.id})
    await session.commit()
    return WorkflowRunDetailResponse.model_validate(run)


@router.get("/v1/app-builder/runs/{run_id}/events")
async def app_builder_events(
    run_id: str,
    user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_db),
    last_event_id: int | None = Header(default=None, alias="Last-Event-ID"),
) -> StreamingResponse:
    run = await session.get(WorkflowRun, run_id)
    if run is None or not run.status.startswith("builder_"):
        raise HTTPException(status_code=404, detail="App Builder run not found")
    await project_access(session, run.project_id, user, "viewer")
    starting_id = max(last_event_id or 0, 0)

    async def stream() -> AsyncIterator[str]:
        last_id = starting_id
        keepalive_at = datetime.now(timezone.utc)
        while True:
            async with SessionLocal() as stream_session:
                events = await stream_session.scalars(
                    select(WorkflowEvent)
                    .where(
                        WorkflowEvent.workflow_run_id == run_id,
                        WorkflowEvent.id > last_id,
                    )
                    .order_by(WorkflowEvent.id.asc())
                    .limit(100)
                )
                rows = events.all()
                current_run = await stream_session.get(WorkflowRun, run_id)
            sent = False
            for event in rows:
                data = json.dumps(
                    WorkflowEventResponse.model_validate(event).model_dump(mode="json"),
                    separators=(",", ":"),
                )
                yield f"id: {event.id}\nevent: {event.kind}\ndata: {data}\n\n"
                last_id = event.id
                sent = True
            if current_run is None or (
                current_run.status in {"builder_completed", "builder_failed", "builder_cancelled"}
                and not sent
            ):
                return
            now = datetime.now(timezone.utc)
            if (now - keepalive_at).total_seconds() >= 15:
                yield ": keepalive\n\n"
                keepalive_at = now
            await asyncio.sleep(1)

    return StreamingResponse(
        stream(),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "Connection": "keep-alive", "X-Accel-Buffering": "no"},
    )
